// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo_proto/demo_proto.proto

package demo_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DemoProtoHelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoProtoHelloRequest) Reset()         { *m = DemoProtoHelloRequest{} }
func (m *DemoProtoHelloRequest) String() string { return proto.CompactTextString(m) }
func (*DemoProtoHelloRequest) ProtoMessage()    {}
func (*DemoProtoHelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_proto_365ad6d814a9a40a, []int{0}
}
func (m *DemoProtoHelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoProtoHelloRequest.Unmarshal(m, b)
}
func (m *DemoProtoHelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoProtoHelloRequest.Marshal(b, m, deterministic)
}
func (dst *DemoProtoHelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoProtoHelloRequest.Merge(dst, src)
}
func (m *DemoProtoHelloRequest) XXX_Size() int {
	return xxx_messageInfo_DemoProtoHelloRequest.Size(m)
}
func (m *DemoProtoHelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoProtoHelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DemoProtoHelloRequest proto.InternalMessageInfo

func (m *DemoProtoHelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DemoProtoHelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoProtoHelloResponse) Reset()         { *m = DemoProtoHelloResponse{} }
func (m *DemoProtoHelloResponse) String() string { return proto.CompactTextString(m) }
func (*DemoProtoHelloResponse) ProtoMessage()    {}
func (*DemoProtoHelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_proto_365ad6d814a9a40a, []int{1}
}
func (m *DemoProtoHelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoProtoHelloResponse.Unmarshal(m, b)
}
func (m *DemoProtoHelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoProtoHelloResponse.Marshal(b, m, deterministic)
}
func (dst *DemoProtoHelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoProtoHelloResponse.Merge(dst, src)
}
func (m *DemoProtoHelloResponse) XXX_Size() int {
	return xxx_messageInfo_DemoProtoHelloResponse.Size(m)
}
func (m *DemoProtoHelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoProtoHelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DemoProtoHelloResponse proto.InternalMessageInfo

func (m *DemoProtoHelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DemoProtoHelloRequest)(nil), "demo_proto.DemoProtoHelloRequest")
	proto.RegisterType((*DemoProtoHelloResponse)(nil), "demo_proto.DemoProtoHelloResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	SendHelpInfoWithGetMethod(ctx context.Context, in *DemoProtoHelloRequest, opts ...grpc.CallOption) (*DemoProtoHelloResponse, error)
	SendInfoWithPostMethod(ctx context.Context, in *DemoProtoHelloRequest, opts ...grpc.CallOption) (*DemoProtoHelloResponse, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SendHelpInfoWithGetMethod(ctx context.Context, in *DemoProtoHelloRequest, opts ...grpc.CallOption) (*DemoProtoHelloResponse, error) {
	out := new(DemoProtoHelloResponse)
	err := c.cc.Invoke(ctx, "/demo_proto.Hello/SendHelpInfoWithGetMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) SendInfoWithPostMethod(ctx context.Context, in *DemoProtoHelloRequest, opts ...grpc.CallOption) (*DemoProtoHelloResponse, error) {
	out := new(DemoProtoHelloResponse)
	err := c.cc.Invoke(ctx, "/demo_proto.Hello/SendInfoWithPostMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	SendHelpInfoWithGetMethod(context.Context, *DemoProtoHelloRequest) (*DemoProtoHelloResponse, error)
	SendInfoWithPostMethod(context.Context, *DemoProtoHelloRequest) (*DemoProtoHelloResponse, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SendHelpInfoWithGetMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoProtoHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SendHelpInfoWithGetMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo_proto.Hello/SendHelpInfoWithGetMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SendHelpInfoWithGetMethod(ctx, req.(*DemoProtoHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_SendInfoWithPostMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoProtoHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SendInfoWithPostMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo_proto.Hello/SendInfoWithPostMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SendInfoWithPostMethod(ctx, req.(*DemoProtoHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "demo_proto.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHelpInfoWithGetMethod",
			Handler:    _Hello_SendHelpInfoWithGetMethod_Handler,
		},
		{
			MethodName: "SendInfoWithPostMethod",
			Handler:    _Hello_SendInfoWithPostMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo_proto/demo_proto.proto",
}

func init() {
	proto.RegisterFile("demo_proto/demo_proto.proto", fileDescriptor_demo_proto_365ad6d814a9a40a)
}

var fileDescriptor_demo_proto_365ad6d814a9a40a = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0x49, 0xcd, 0xcd,
	0x8f, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x47, 0x30, 0xf5, 0xc0, 0xa4, 0x10, 0x17, 0x42, 0x44,
	0x4a, 0x26, 0x3d, 0x3f, 0x3f, 0x3d, 0x27, 0x55, 0x3f, 0xb1, 0x20, 0x53, 0x3f, 0x31, 0x2f, 0x2f,
	0xbf, 0x24, 0xb1, 0x24, 0x33, 0x3f, 0xaf, 0x18, 0xa2, 0x52, 0x49, 0x9b, 0x4b, 0xd4, 0x25, 0x35,
	0x37, 0x3f, 0x00, 0xc4, 0xf1, 0x48, 0xcd, 0xc9, 0xc9, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02,
	0xb3, 0x95, 0x8c, 0xb8, 0xc4, 0xd0, 0x15, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x49, 0x70,
	0xb1, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xc3, 0x34, 0xc0, 0xb8, 0x46, 0x6f, 0x18, 0xb9, 0x58,
	0xc1, 0x6a, 0x85, 0x0a, 0xb8, 0x24, 0x83, 0x53, 0xf3, 0x52, 0x3c, 0x52, 0x73, 0x0a, 0x3c, 0xf3,
	0xd2, 0xf2, 0xc3, 0x33, 0x4b, 0x32, 0xdc, 0x53, 0x4b, 0x7c, 0x53, 0x4b, 0x32, 0xf2, 0x53, 0x84,
	0x14, 0xf5, 0x90, 0x3c, 0x81, 0xd5, 0x45, 0x52, 0x4a, 0xf8, 0x94, 0x40, 0xdc, 0xa1, 0xc4, 0xd3,
	0x74, 0xf9, 0xc9, 0x64, 0x26, 0x36, 0x21, 0x16, 0xfd, 0xf4, 0xd4, 0x12, 0xa1, 0x42, 0x2e, 0x31,
	0x90, 0x8d, 0x30, 0xdb, 0x02, 0xf2, 0x8b, 0xa9, 0x6c, 0x9d, 0x00, 0xd8, 0x3a, 0x2e, 0x25, 0x56,
	0xfd, 0x82, 0xfc, 0xe2, 0x12, 0x2b, 0x46, 0xad, 0x24, 0x36, 0xb0, 0x7a, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x33, 0x39, 0x1b, 0x6b, 0x9f, 0x01, 0x00, 0x00,
}
